version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    groups:
      npm_and_yarn:
        applies-to: security-updates
        patterns:
          - "*"
